#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_DSR_VERSION=${VERSION_STRING[2]}
ELECTRUM_DSR_VERSION=${ELECTRUM_DSR_VERSION#\'}
ELECTRUM_DSR_VERSION=${ELECTRUM_DSR_VERSION%\'}
export ELECTRUM_DSR_VERSION
